"""empty message

Revision ID: 481a2a698636
Revises: 9b8e4c3ea067
Create Date: 2020-01-09 22:37:27.253549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481a2a698636'
down_revision = '9b8e4c3ea067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cars_ship_to_fkey', 'cars', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('cars_ship_to_fkey', 'cars', 'dealers', ['ship_to'], ['dealer_code'])
    # ### end Alembic commands ###
