"""empty message

Revision ID: 6c01f0d36f9c
Revises: 73f30d3aa840
Create Date: 2020-01-08 21:42:18.850152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c01f0d36f9c'
down_revision = '73f30d3aa840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_models',
    sa.Column('model_code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('model_code')
    )
    op.create_table('dealers',
    sa.Column('dealer_code', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('dealer_code')
    )
    op.add_column('cars', sa.Column('car_model', sa.String(), nullable=True))
    op.add_column('cars', sa.Column('opt_code', sa.String(), nullable=True))
    op.add_column('cars', sa.Column('ship_to', sa.String(), nullable=True))
    op.add_column('cars', sa.Column('sold_to', sa.String(), nullable=True))
    op.create_foreign_key(None, 'cars', 'car_models', ['car_model'], ['model_code'])
    op.create_foreign_key(None, 'cars', 'dealers', ['sold_to'], ['dealer_code'])
    op.create_foreign_key(None, 'cars', 'dealers', ['ship_to'], ['dealer_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_column('cars', 'sold_to')
    op.drop_column('cars', 'ship_to')
    op.drop_column('cars', 'opt_code')
    op.drop_column('cars', 'car_model')
    op.drop_table('dealers')
    op.drop_table('car_models')
    # ### end Alembic commands ###
