"""empty message

Revision ID: 9b8e4c3ea067
Revises: 6c01f0d36f9c
Create Date: 2020-01-08 22:24:21.630986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b8e4c3ea067'
down_revision = '6c01f0d36f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'created_date')
    # ### end Alembic commands ###
