"""empty message

Revision ID: 031d87a592c7
Revises: fdf88ddd9f25
Create Date: 2020-01-13 16:41:27.094963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031d87a592c7'
down_revision = 'fdf88ddd9f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealers', sa.Column('car_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dealers', 'car_count')
    # ### end Alembic commands ###
