"""empty message

Revision ID: 2325d23a6b62
Revises: 904bc30b6977
Create Date: 2020-02-10 17:38:36.943298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2325d23a6b62'
down_revision = '904bc30b6977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraper_logs', sa.Column('run_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraper_logs', 'run_type')
    # ### end Alembic commands ###
