"""empty message

Revision ID: 904bc30b6977
Revises: 93d9edc241d8
Create Date: 2020-01-23 14:32:10.569015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904bc30b6977'
down_revision = '93d9edc241d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraper_logs', sa.Column('success', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraper_logs', 'success')
    # ### end Alembic commands ###
