"""empty message

Revision ID: 93d9edc241d8
Revises: 031d87a592c7
Create Date: 2020-01-23 12:38:36.174258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d9edc241d8'
down_revision = '031d87a592c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('found_cars', sa.Integer(), nullable=True),
    sa.Column('run_start', sa.DateTime(), nullable=True),
    sa.Column('run_end', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cars', sa.Column('serial_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'serial_number')
    op.drop_table('scraper_logs')
    # ### end Alembic commands ###
