"""empty message

Revision ID: d9ed6886ca70
Revises: 
Create Date: 2020-06-04 08:55:42.953170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
#revision = 'd9ed6886ca70'
revision = '2325d23a6b62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_models',
    sa.Column('model_code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('model_code')
    )
    op.create_table('dealers',
    sa.Column('dealer_code', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('car_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('dealer_code')
    )
    op.create_table('scraper_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('found_cars', sa.Integer(), nullable=True),
    sa.Column('run_start', sa.DateTime(), nullable=True),
    sa.Column('run_end', sa.DateTime(), nullable=True),
    sa.Column('run_type', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('serial_number', sa.Integer(), nullable=True),
    sa.Column('ext_color', sa.String(), nullable=True),
    sa.Column('int_color', sa.String(), nullable=True),
    sa.Column('car_model', sa.String(), nullable=True),
    sa.Column('opt_code', sa.String(), nullable=True),
    sa.Column('sold_to', sa.String(), nullable=True),
    sa.Column('ship_to', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('model_year', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['car_model'], ['car_models.model_code'], ),
    sa.ForeignKeyConstraint(['sold_to'], ['dealers.dealer_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    op.drop_table('scraper_logs')
    op.drop_table('dealers')
    op.drop_table('car_models')
    # ### end Alembic commands ###
